pin map was implemented
NastyaKuvi/keksobooking pull request #1
Opened 2017-12-16 13:33 UTC by NastyaKuvi

2017-12-16 15:06 UTC, oliktva requested changes
Надо доработать

2017-12-16 15:06 UTC, oliktva commented on js/map.js
> +var getCorrectStringNumber = function (number) {
По названию метода непонятно что он делает

2017-12-16 15:06 UTC, oliktva commented on js/map.js
> +var getUnicTitle = function () {
ты можешь это лучше сделать, тыжматематик

2017-12-16 15:06 UTC, oliktva commented on js/map.js
> +var getType = function () {
эта и getTime делаю почти одно и то же, можно сделать одну функцию и передавать на вход массив

2017-12-16 15:06 UTC, oliktva commented on js/map.js
> +var getUnicFeatures = function (length) {
тыжматематик

2017-12-16 15:06 UTC, oliktva commented on js/map.js
> +    resultdata.push(object);
👍

2017-12-16 15:06 UTC, oliktva commented on js/map.js
> +var getTypeName = function (type) {
не очень понятно зачем это, ты мне завтра объясни

2017-12-16 15:06 UTC, oliktva commented on js/map.js
> +  offerDialog.querySelector('.dialog__title').querySelector('img').setAttribute('src', data.author.avatar);
что-то не то с отступами

2017-12-16 15:06 UTC, oliktva commented on js/map.js
> +var createNewOffer = function (data) {
render, у всех функций, что добавляют что-то в DOM префикс render

2018-01-10 18:59 UTC, NastyaKuvi commented on js/map.js
> +var getCorrectStringNumber = function (number) {
могу изменить имя на что-то вроде formatUserNumberToString или могу его удалить к чертям и по дефолту приписывать всегда ноль,  но первый вариант мне конечно нравится больше. Что скажешь?

2018-01-10 19:45 UTC, NastyaKuvi commented on js/map.js
> +var getUnicTitle = function () {
ок

2018-01-10 19:53 UTC, NastyaKuvi commented on js/map.js
> +var getType = function () {
ок

2018-01-10 19:54 UTC, NastyaKuvi commented on js/map.js
> +var getUnicFeatures = function (length) {
ок
P.S. сама тыжматематик...

2018-01-10 19:55 UTC, NastyaKuvi commented on js/map.js
> +    resultdata.push(object);
это типо все норм  я надеюсь?))

2018-01-10 20:08 UTC, NastyaKuvi commented on js/map.js
> +var getTypeName = function (type) {
ну короче я подумала и сделала проще

2018-01-10 20:10 UTC, NastyaKuvi commented on js/map.js
> +var createNewOffer = function (data) {
ок

2018-01-10 20:12 UTC, NastyaKuvi commented on js/map.js
> +  offerDialog.querySelector('.dialog__title').querySelector('img').setAttribute('src', data.author.avatar);
https://pp.userapi.com/c425822/v425822035/1ed8/h9nztaU59uo.jpg

2018-01-12 12:12 UTC, oliktva commented on js/map.js
> +var getCorrectStringNumber = function (number) {
он у тебя не всегда string возвращает кстати
по предложенному названию все еще непонятно что он делает

2018-01-12 12:12 UTC, oliktva commented on js/map.js
> +    resultdata.push(object);
ага

2018-01-12 12:13 UTC, oliktva commented on js/map.js
> +  offerDialog.querySelector('.dialog__title').querySelector('img').setAttribute('src', data.author.avatar);
пробельчиков не хватает

2018-01-12 13:57 UTC, NastyaKuvi commented on js/map.js
> +var getCorrectStringNumber = function (number) {
formatUserNumber

2018-01-12 13:57 UTC, NastyaKuvi commented on js/map.js
> +  offerDialog.querySelector('.dialog__title').querySelector('img').setAttribute('src', data.author.avatar);
хоть убей не понимаю каких, eslint ничего не выдает

2018-01-12 13:59 UTC, oliktva commented on js/map.js
> +  offerDialog.querySelector('.dialog__title').querySelector('img').setAttribute('src', data.author.avatar);
у меня не обновилось видимо, теперь ок

2018-01-15 09:09 UTC, oliktva requested changes

2018-01-15 09:09 UTC, oliktva commented on js/map.js
> +var getUnicTitle = function (index) {
функции, где ты лишь вызываешь другие функции лишние, это можно делать сразу там, где ты их вызываешь.

2018-01-15 09:09 UTC, oliktva commented on js/map.js
> +for (var i = 0; i < data.length; i++) {
давай сделаем это через метод forEach

2018-01-18 18:50 UTC, NastyaKuvi commented on js/map.js
> +var getUnicTitle = function (index) {
ок

2018-01-19 08:31 UTC, oliktva approved these changes
👍

2018-01-19 08:37 UTC, merged