Feedback on user behavior with pin map was implemented
NastyaKuvi/keksobooking pull request #2
Opened 2018-01-21 17:38 UTC by NastyaKuvi

2018-01-23 09:14 UTC, oliktva requested changes

2018-01-23 09:14 UTC, oliktva commented on js/map.js
> +var setActivePin = function (curNode, curData) {
надо разделить определение текущего активного Пина, установку активного Пина и отрисовку диалогового окна

2018-01-23 09:14 UTC, oliktva commented on js/map.js
> +  var htmlString = '<img src="' + dataElem.author.avatar + '" class="rounded" width="40" height="40">';
а давай переименуем htmlString в что-то типа imgElement?

2018-01-23 09:14 UTC, oliktva commented on js/map.js
> +    setActivePin(evt.currentTarget, dataElem);
надо создать функцию, которая будет включать в себя установку пина активным и открытие диалогового окна

2018-01-23 09:14 UTC, oliktva commented on js/map.js
> +  offerDialog.replaceChild(renderLodgeElement(data.offer), offerDialog.querySelector('.dialog__panel'));
нормально же было что он вынесен в переменную

2018-01-23 09:14 UTC, oliktva commented on js/map.js
> +    offerDialog.classList.remove('hidden');
давай hidden вынесем в константу

2018-01-23 09:14 UTC, oliktva commented on js/map.js
> +var data = createData(8).sort(function (a, b) {
и 8 тоже

2018-01-23 09:14 UTC, oliktva commented on js/map.js
> +offerDialog.querySelector('.dialog__close').addEventListener('click', function () {
и это в переменную

2018-01-23 09:14 UTC, oliktva commented on js/map.js
> +  hideCurrentOfferDialog();
ты же это сделала на 168 строке?

2018-01-24 19:29 UTC, NastyaKuvi commented on js/map.js
> +  var htmlString = '<img src="' + dataElem.author.avatar + '" class="rounded" width="40" height="40">';
ок

2018-01-24 19:31 UTC, NastyaKuvi commented on js/map.js
> +  offerDialog.replaceChild(renderLodgeElement(data.offer), offerDialog.querySelector('.dialog__panel'));
ок

2018-01-24 19:32 UTC, NastyaKuvi commented on js/map.js
> +    offerDialog.classList.remove('hidden');
ок

2018-01-24 19:32 UTC, NastyaKuvi commented on js/map.js
> +var data = createData(8).sort(function (a, b) {
ок

2018-01-24 19:36 UTC, NastyaKuvi commented on js/map.js
> +offerDialog.querySelector('.dialog__close').addEventListener('click', function () {
ок

2018-01-24 19:39 UTC, NastyaKuvi commented on js/map.js
> +  hideCurrentOfferDialog();
ну это две разных вещи совершенно, но ок сделаю по другому немного, так и правильней наверно

2018-01-24 19:42 UTC, NastyaKuvi commented on js/map.js
> +var setActivePin = function (curNode, curData) {
не вижу смысла разделять  определение текущего активного Пина, установку активного Пина, так как текущий активный пин у меня в переменной, и они должны быть в одной функции так как с текущего убираем хидден, новому сетим, и сетим его в текущий.
ппеременную сделала чтобы каждый раз не бекать по документу в поисках активного пина
Так что я делю на два метода

2018-01-24 19:56 UTC, NastyaKuvi commented on js/map.js
> +  offerDialog.replaceChild(renderLodgeElement(data.offer), offerDialog.querySelector('.dialog__panel'));
не ок, я делаю реплейс диалог панели, поэтому после первого пина моя переменная будет уже не то что мне надо

2018-01-30 14:37 UTC, oliktva commented on js/map.js
> +var KEY_MAP = {
KEY_MAP -> KeyMap

2018-01-30 14:37 UTC, oliktva commented on js/map.js
> +var KEY_MAP = {
ну и остальные мапы переименую (не их свойства ток, свойства ок)

2018-01-31 08:37 UTC, oliktva commented on js/map.js
> +  shuffledTitles = shuffleArray(DataMap.TITLES);
а почему мы их глобально объявили?

2018-02-01 12:55 UTC, oliktva approved these changes

2018-02-01 18:36 UTC, merged